### ISSUE TITLE
Got a 411

### ISSUE THREAD

**Issue by BadTudou-zz** [govi2010/oauth2-evernote#1]
OAuthException: Invalid auth/bad request (got a 411, expected HTTP/1.1 20X or a redirect) 
in /evernote/lib/Evernote/Client.php on line 48

**Comment by govi2010** [comment]
Sorry for late replay but i will check this on week end.

**Comment by BadTudou-zz** [comment]
Thank you very much！
Before I made a question to the developers of Evernote, I found that I may have set up a proxy for the sake of the terminal。
So I decided to close this question, very sorry to forget to turn it off.
